<?php


function motor_permission() {
  return array(
    'game admin' => array(
      'title' => t('Create new game (nodequeue)'),
    )
  );
}

function motor_menu() {
  global $quid;
  $items['motor/%'] = array(
    'title' => 'Task reset',
    'page callback' => 'motor_node',
    'page arguments' => array(1),
    'access arguments' => array('access content'),
  );

  $items['stat'] = array(
    'title' => 'Task reset',
    'page callback' => 'motor_stat',
    'access arguments' => array('access content'),
  );

  $items['game_admin'] = array(
    'title' => 'Game admin',
    'page callback' => 'motor_game_admin',
    'access arguments' => array('game admin'),
  );
  
  return $items;
}

function motor_node($nid) {
  $node = node_load($nid);
  $node = node_view($node);
  print drupal_render($node);
}



function game_of_place($nid) {
  $query = db_query('SELECT * FROM {nodequeue_nodes} WHERE nid = :nid', array(':nid' => $nid))->fetchObject();
  return $query->qid;
}

function nextplace($nid) {

  $node = node_load($nid);
  
  $queues = nodequeue_load_queues_by_type($node->type);
  $subqueues = nodequeue_get_subqueues_by_node($queues, $node);
  
  $query = db_query('SELECT * FROM {nodequeue_nodes} WHERE nid = :nid', array(':nid' => $nid))->fetchObject();
  $query = db_query('SELECT nid, position FROM {nodequeue_nodes}
                    WHERE position = :pos
                    AND qid = :qid',
                    array(':pos' => $query->position + 1,
                          ':qid' => $query->qid))->fetchObject();
  
  (is_object($query)) ? $nnid = $query->nid : $nnid = 0;
  return $nnid;
}


/**
 * Implements hook_form_alter().
 */
function motor_form_alter(&$form, &$form_state, $form_id) {
  global $user;
  //dpm($form_id);
 
  $form['field_source_place']['und']['#default_value'][] = arg(3);
  
  $form['field_source_place']['und']['#type'] = 'hidden';
  
  
  if ($form_id == "tipp_node_form") {
    $form['actions']['submit']['#value'] = 'Ott van!';
    $form['actions']['skip'] = array(
      '#markup' => l('> Kihagyom, következő helyszín', '/node/add/tipp/' . nextplace(arg(3))),
      '#weight' => 6,
      '#prefix' => '<div class="skipButton">',
      '#suffix' => '</div>',
    );
    $form['actions']['geomob'] = array(
      '#markup' => 'Itt vagyok',
      '#weight' => 6,
      '#prefix' => '<div id="geoMOB" class="skipButton imhere"><a href="#">',
      '#suffix' => '</a></div>',
    );
    
    /*
    $form['fb_comments'] = array(
      '#markup' => '<div class="fb-comments" data-href="http://lattammar.nemkf.com/node/' . arg(3) . '" data-width="100%" data-numposts="5"></div>',
      '#weight' => 100,
    );
    */
    
    
    $query = db_query('SELECT * FROM {nodequeue_nodes} WHERE nid = :nid', array(':nid' => arg(3)))->fetchObject();
    $query = db_query('SELECT * FROM {field_data_field_qid} WHERE field_qid_value = :qid', array(':qid' => $query->qid))->fetchObject();
    if (!empty($query)) {
      $def = node_load($query->entity_id);
      $lat = $def->field_point['und'][0]['lat'];
      $lon = $def->field_point['und'][0]['lon'];
      
      $form['field_point']['und'][0]['geom']['#default_value']['lat'] = $lat;
      $form['field_point']['und'][0]['geom']['#default_value']['lon'] = $lon;
    }
    $prev_tipp_nid = arg(4);
    if (isset($prev_tipp_nid)) {
      $prev_tipp = node_load(arg(4));
      $lat = $prev_tipp->field_point['und'][0]['lat'];
      $lon = $prev_tipp->field_point['und'][0]['lon'];
      
      $form['field_point']['und'][0]['geom']['#default_value']['lat'] = $lat;
      $form['field_point']['und'][0]['geom']['#default_value']['lon'] = $lon;
    }
  }
  
  if ($form_id == 'nodequeue_edit_queue_form') {
    $form['#submit'][] = 'motor_nq_usersave';
  }
  
  if ($form_id == 'views_form_games_admin_block_1') {
    if (isset($form['qids'])) {
      foreach ($form['qids']['#options'] as $key=>$value) {
        $uid = (int)variable_get($key . '_user', 0);
        dpm($uid . ':' . $key . ':' . $user->uid);
        if ($uid == 0) {
          variable_set($key . '_user', 1);
        }
        if ($uid != $user->uid) {
          unset($form['qids']['#options'][$key]);
        }
      }
    }
  }

}

function motor_nq_usersave($form, $form_state) {
  global $user;
  variable_set($form_state['values']['qid'] . '_user', $user->uid);
}

function prox2word($prox) {
  
  $node = node_load(arg(1));
  $place_nid = $node->field_source_place['und'][0]['nid'];
  $output = array();
  $output['text'] = 'A tipped ' . (int)($prox) . ' méterre van a helyszíntől!';
  if ($prox < 200) {
    
    $output['text'].= "ez igen!";
    $cookies = array();
    if (isset($_COOKIE['Drupal_visitor_lattammar'])) {
      $cookies = explode(',', $_COOKIE['Drupal_visitor_lattammar']);
    }
    if (!in_array($place_nid, $cookies)) {
      $cookies[] = $place_nid;
    }
    $cookies_save = implode(',', $cookies);
    user_cookie_save(array('lattammar' => $cookies_save));
  }
  $output['int'] = (int)$prox;
  return $output;
}


function solved($nid) {
  if (!isset($_COOKIE['Drupal_visitor_lattammar'])) {
    return;
  }
  $nids = explode(',' ,$_COOKIE['Drupal_visitor_lattammar']);
  $output = '';
  if (in_array($nid, $nids)) {
    $output.= '<div class="solved"></div>';;
  }
  return $output;
}

function solvedDB($nid) {
  
}

function motor_generate_machine_name($name) {
  $unwanted_array = array('Š'=>'S', 'š'=>'s', 'Ž'=>'Z', 'ž'=>'z', 'À'=>'A', 'Á'=>'A', 'Â'=>'A', 'Ã'=>'A', 'Ä'=>'A', 'Å'=>'A', 'Æ'=>'A', 'Ç'=>'C', 'È'=>'E', 'É'=>'E',
                          'Ê'=>'E', 'Ë'=>'E', 'Ì'=>'I', 'Í'=>'I', 'Î'=>'I', 'Ï'=>'I', 'Ñ'=>'N', 'Ò'=>'O', 'Ó'=>'O', 'Ô'=>'O', 'Õ'=>'O', 'Ö'=>'O', 'Ø'=>'O', 'Ù'=>'U',
                          'Ú'=>'U', 'Û'=>'U', 'Ü'=>'U', 'Ý'=>'Y', 'Þ'=>'B', 'ß'=>'Ss', 'à'=>'a', 'á'=>'a', 'â'=>'a', 'ã'=>'a', 'ä'=>'a', 'å'=>'a', 'æ'=>'a', 'ç'=>'c',
                          'è'=>'e', 'é'=>'e', 'ê'=>'e', 'ë'=>'e', 'ì'=>'i', 'í'=>'i', 'î'=>'i', 'ï'=>'i', 'ð'=>'o', 'ñ'=>'n', 'ò'=>'o', 'ó'=>'o', 'ô'=>'o', 'õ'=>'o',
                          'ö'=>'o', 'ø'=>'o', 'ù'=>'u', 'ú'=>'u', 'û'=>'u', 'ý'=>'y', 'þ'=>'b', 'ÿ'=>'y', 'ő' => 'o', 'ü' => 'u', 'ű' => 'u' );
  $name = strtolower($name);
  $name = strtr($name, $unwanted_array );
  return $name;
}

function motor_create_nq($name) {
  
  
  $r = 0;
  
  
  $machine_name = motor_generate_machine_name($name);


  
  $nname = $machine_name;
  while (nodequeue_machine_name_exists($nname)) {
    $r++;
    $nname = $name . '_' . $r;
  }
  
  $machine_name = $nname;



  
  $output = '<a href="#" onclick="geoMOB();">GET</a>';
  $nodequeue = new stdClass;
  $nodequeue->api_version = 2;
  $nodequeue->name = $machine_name;
  $nodequeue->title = $name;
  $nodequeue->subqueue_title = '';
  $nodequeue->size = 0;
  $nodequeue->link = '';
  $nodequeue->link_remove = '';
  $nodequeue->owner = 'nodequeue';
  $nodequeue->show_in_ui = 1;
  $nodequeue->show_in_tab = 1;
  $nodequeue->show_in_links = 0;
  $nodequeue->insert_at_front = 0;
  $nodequeue->reference = '0';
  $nodequeue->reverse = 0;
  $nodequeue->i18n = 0;
  $nodequeue->roles = array();
  $nodequeue->types = array(
    0 => 'place',
  );
  
 

  $nq = nodequeue_save($nodequeue);
  $queue = nodequeue_load($nq);
  nodequeue_add_subqueue($queue, $name);
  drupal_set_message($nq . ' nodequeue saved.');

  
  
  return $nq;
}

function motor_delete_nq($name) {
  $machine_name = motor_generate_machine_name($name);
  nodequeue_delete($machine_name);
}


function motor_block_info() {
  $blocks = array();
  $blocks['facebook_comments'] = array(
    'info' => t('FB comments'),
  );
  $blocks['facebook_like'] = array(
    'info' => t('FB like&share'),
  );
  $blocks['create_new_game'] = array(
    'info' => t('Create new game'),
  );

  return $blocks;
}

function motor_block_view($delta = '') {
  $block = array();
  switch ($delta) {
    case 'facebook_comments':
      $block['subject'] = '';
      $block['content'] = '<div class="fb-comments" data-href="http://lattammar.nemkf.com/node/' . arg(3) . '" data-width="100%" data-numposts="5"></div>';
      break;
    case 'facebook_like':
      $block['subject'] = '';
      $block['content'] = '<div class="fb-like" data-href="https://lattammar.nemkf.com/node/' . arg(3) . '" data-layout="standard" data-action="like" data-show-faces="true" data-share="true"></div>';
      break;
     case 'create_new_game':

      $form = drupal_get_form('motor_game_admin_form');
      $block['subject'] = '';
      $block['content'] = drupal_render($form);
      break;
  }
  return $block;
}

function motor_create_places_from_mail($nid) {
  $node = node_load($nid); 
  $user = user_load_by_mail($node->field_from['und'][0]['value']);
  $uid = $user->uid;
  watchdog('userid', $uid);
  $subject = $node->field_subject['und'][0]['value'];
  foreach ($node->field_photos['und'] as $photo) {
    
    $node = new stdClass();  // Create a new node object
    $node->type = 'place';  // Content type
    $node->language = LANGUAGE_NONE;  // Or e.g. 'en' if locale is enabled
    
    node_object_prepare($node);
    $node->uid = $uid;
    // Create image File object and associate with Image field.
    $file = new StdClass();
    $file->uid = $uid;
    $file->uri = $photo['uri'];
    $file->filemime = file_get_mimetype($file->uri);
    $file->status = 0;
    $file->display = 1;
    $file->description = "";  
    $dest = file_default_scheme() . '://';
    $file = file_copy($file, $dest);
    $node->field_photo[LANGUAGE_NONE][0] = (array)$file;
    $node = node_submit($node);
    node_save($node);
    
    if (!empty($subject)) {
      $fq = db_query('SELECT * FROM nodequeue_queue WHERE name = :name',
                     array(':name' => $subject))->fetchObject();
     
      if (!empty($fq)) {
        $qid = $fq->qid;
        $pos = db_query('SELECT * FROM nodequeue_nodes;');
        foreach ($pos as $row) {
          db_query('UPDATE nodequeue_nodes SET position = :position',
                   array(':position'=>$row->position+1));
        }
        
        
        
        $node_to_queue = db_query('INSERT INTO nodequeue_nodes (qid, sqid, nid, position)
                                  VALUES (:qid,:sqid,:nid,:position)',
                                  array(':qid' => $qid,
                                        ':sqid' => $qid,
                                        ':nid' => $node->nid,
                                        ':position' => 1));
      } 
    }
    
  }
  
}


function motor_game_admin_form($form, &$form_state) {
  /*
  global $user;
  $results = db_query('SELECT * FROM {node} WHERE type = :type AND uid = :user',
                      array(':type' => 'place',
                            ':user' => $user->uid));
   $form = array();
  foreach ($results as $row) {
    $node = node_load($row->nid);
    $form['place_' . $row->nid] = array(
      '#markup' => '<img src="' . image_style_url('box', $node->field_photo['und'][0]['uri']) . '">',
    );
    $form['place_' . $row->nid . '_selected'] = array(
      '#type' => 'checkbox',
    );
  }
  */
   $form['game_name'] = array(
    '#title' => t('2. Create new game'),
    '#type' => 'textfield',
    '#default_value' => t('name of the game'),
   );
   
   $form['game_save'] = array(
    '#value' => 'Mentés',
    '#type' => 'submit',
   );
   return $form;
}

function motor_game_admin_form_submit($form, &$form_state) {
  global $user;
  
  $nq = motor_create_nq($form_state['values']['game_name']);
  variable_set($nq . '_user', $user->uid);
}

function motor_game_admin() {
  $output = 'ok';
 
  $form = drupal_get_form('motor_game_admin_form');
  //$output.= drupal_render($form);
  
  $subject = 'napi';
  $node = node_load(320);
  
  
  
  return $output;
}

function motor_nq_perm($qid, $uid) {
  global $user;
  $uid = variable_get($qid . '_user');
  if ($user == $uid) {
    return true;
  } else {
    return false;
  }
}


function calcdist($tipnid) {
  //function distance($lat1, $lon1, $lat2, $lon2, $unit)
  
  if (empty($tipnid)) {
    $tipnid = arg(1);
    
  } else {
    
  }
  $tip_node = node_load($tipnid);
  $placenid = $tip_node->field_source_place['und'][0]['nid'];
  
  //tip coordinates
  
  $lat1 = $tip_node->field_point['und'][0]['lat'];
  $lon1 = $tip_node->field_point['und'][0]['lon'];

  //place coordinates
  $place_node = node_load($placenid);
  if (count($place_node->field_place) > 0) {
    $lat2 = $place_node->field_place['und'][0]['lat'];
    $lon2 = $place_node->field_place['und'][0]['lon'];
  } else {
    $lat2 = $place_node->field_place_manual['und'][0]['lat'];
    $lon2 = $place_node->field_place_manual['und'][0]['lon'];
  }

  $theta = $lon1 - $lon2;
  $dist = sin(deg2rad($lat1)) * sin(deg2rad($lat2)) +  cos(deg2rad($lat1)) * cos(deg2rad($lat2)) * cos(deg2rad($theta));
  $dist = acos($dist);
  $dist = rad2deg($dist);
  $miles = $dist * 60 * 1.1515;
  $unit = strtoupper($unit);

  
    return round($dist*100000);
  

}

























